import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Header from "./components/Header";
import FloatingMenu from "./components/FloatingMenu";
import FloatingCTA from "./components/FloatingCTA";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=ranade@700,300,2,701,401,101,100,400,1,500,501,301&f[]=excon@400,900,700,500,300,100,1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <ClientBody>
          {/* 全ページ共通のフローティング要素 */}
          <FloatingMenu />
          <FloatingCTA />
          
          <div className="min-h-screen bg-white">
            <main>{children}</main>
            
            {/* Footer - 全ページ共通 */}
            <footer className="bg-gray-900 text-white py-20">
              <div className="container mx-auto px-4">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
                  <div>
                    <Image
                      src="/images/logo_w.png"
                      alt="薬の桃太郎"
                      width={120}
                      height={40}
                      className="mb-6 w-auto h-20"
                    />
                  </div>
                  <div>
                    <h4 className="font-bold mb-4">診療メニュー</h4>
                    <ul className="space-y-2 text-sm">
                      <li><Link href="#" className="hover:text-blue-400">男性AGA</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">ピル処方</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">ED治療</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">こころのお悩み</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">女性AGA</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">眠りのお悩み</Link></li>
                    </ul>
                  </div>
                  <div>
                    <h4 className="font-bold mb-4">サービス</h4>
                    <ul className="space-y-2 text-sm">
                      <li><Link href="#" className="hover:text-blue-400">花粉症</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">ニキビ治療</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">ダイエット漢方</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">高脂血症</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">汗のお悩み</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">まつ毛美容液</Link></li>
                    </ul>
                  </div>
                  <div>
                    <h4 className="font-bold mb-4">企業情報</h4>
                    <ul className="space-y-2 text-sm">
                      <li><Link href="#" className="hover:text-blue-400">運営会社</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">特定商取引法に基づく表示</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">利用規約</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">プライバシーポリシー</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">お知らせ</Link></li>
                      <li><Link href="#" className="hover:text-blue-400">お問い合わせ</Link></li>
                    </ul>
                  </div>
                </div>
                <div className="border-t border-gray-700 pt-8 text-center text-sm text-gray-400">
                  <p>&copy; 2025 薬の桃太郎. All rights reserved.</p>
                </div>
              </div>
            </footer>
          </div>
        </ClientBody>
      </body>
    </html>
  );
}
